### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by kaperrine-dog** [kaperrine-dog/chat-space#15]
# IPアドレス
18.178.62.220

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**①メッセージの投稿日時の表示形式を見本と揃えましょう！**
[現在]
[![Image from Gyazo](https://i.gyazo.com/67956506d2f181753263e5ecbe8add79.png)](https://gyazo.com/67956506d2f181753263e5ecbe8add79)

[見本]
[![Image from Gyazo](https://i.gyazo.com/741d52886a9db679fa9641d9f637b734.png)](https://gyazo.com/741d52886a9db679fa9641d9f637b734)

**②アラートのデザインを見本と揃えましょう！**
（おしゃれなデザインとても良いと思います！ただ、今回はカリキュラムの内容のため見本に近いものをつくっていただくようになっております。お手数ですが修正をお願いいたします。）
[![Image from Gyazo](https://i.gyazo.com/a479778419328b7e37d6bbf422082be5.png)](https://gyazo.com/a479778419328b7e37d6bbf422082be5)

**③画像の非同期通信で、2回に1回くらいの確率で
　1つの送信に対して2つの画像が投稿されてしまう**

※カリキュラムの中にある、模範のchatspaceを参考に、修正をお願いします。
[模範のchatpsace]
https://chat-space-sample.herokuapp.com/

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by kaperrine-dog** [comment]
以下の点にて修正しました。
・メッセージBOXのメッセージ送信時間のフォーマットを修正しました。
・アラートをJavaScriptの標準のものに戻しました。

非同期通信で50％程度の確率で、2回送信されたように見えてしまう現象についてですが、先程TECH::CONNECTでお伺いしたところ、送信時のajax通信が行われるタイミングで、自動更新のajaxで設定しているsetIntervalが動いてしまうと2回送信したように見えてしまうようです。
リロードするとメッセージは1つしか残りません。
特に大きいサイズ（7MB程度）の画像では、aws S3のバケットにアップロードされるまでに時間を要するので、この現象が起こるようです。

以上よろしくお願いします。

**Comment by kaperrine-dog** [comment]
TECH::CONNECTでご対応頂いたメンターさんは
仕様と仰っていました。

**Comment by naru6117** [comment]
ご確認ありがとうございます！
また、詳細の記載ありがとうございます！
ご質問いただきました画像の非同期通信についてですが、社内で改めて確認しましたところ、仕様のため修正不要とのことでした。
ご迷惑をおかけし、申し訳ありません！

その他の項目は確認させて頂いたところ、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
